+----------------+         +-------------+
|    Order       |<>-------| Payment     |
+----------------+         +-------------+
| - orderId      |         | + pay(amount:                       double): void
| - amount       |         | + cancel(): void
+----------------+         +-------------+
                            ^
                            |
                   +--------+---------+
                   |                 |
           +-------+-------+ +-------+-------+
           |               | |               |
    +------+------+ +------+------+ +------+------+
    | WeChatPay   | | AlipayPay    | | UnionPay     |
    +------+------+ +------+------+ +------+------+
    | + pay(amount: double): void | | + pay(amount: double): void | | + pay(amount: double): void |
    | + cancel(): void            | | + cancel(): void            | | + cancel(): void            |
+------------------------------+ +------------------------------+ +------------------------------+
